export const GET_ALL_SUCCESS = 'GET_ALL_SUCCESS';
export const GET_ALL_FAILURE = 'GET_ALL_FAILURE';
export const GET_BY_ZONE = 'GET_BY_ZONE';
export const GET_BY_ZONE_SUCCESS = 'GET_BY_ZONE_SUCCESS';
export const GET_BY_ZONE_FAILURE = 'GET_BY_ZONE_FAILURE';
